# Generated by Django 4.0.1 on 2022-07-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatheruser',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
