# Generated by Django 4.0.1 on 2022-07-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatheruser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatheruser',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weatheruser',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
