# Generated by Django 4.0.1 on 2022-07-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_alter_weatheruser_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatheruser',
            name='days',
            field=models.IntegerField(default=1),
        ),
    ]
